[versions]
kotlin = "2.3.20"
kotlin-wrap = "2026.1.9"
openrndr = "0.5.0-alpha3"
orx = "0.5.0-alpha3"

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-browser = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-browser", version.ref = "kotlin-wrap"}
kotlin-js = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-js", version.ref = "kotlin-wrap"}
kotlin-web = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-web", version.ref = "kotlin-wrap"}

openrndr-application = { group = "org.openrndr", name = "openrndr-application", version.ref = "openrndr" }
openrndr-dds = { group = "org.openrndr", name = "openrndr-dds", version.ref = "openrndr" }
openrndr-draw = { group = "org.openrndr", name = "openrndr-draw", version.ref = "openrndr" }
openrndr-webgl = { group = "org.openrndr", name = "openrndr-webgl", version.ref = "openrndr" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }

