// This file was auto-generated by Gradle
val myApps = mapOf(
    "gradient" to :: gradient,
    "gridOfRotating" to :: gridOfRotating,
    "shadeStyleParam" to :: shadeStyleParam,
    "fabulousPink" to :: fabulousPink,
    "bouncyBubbles" to :: bouncyBubbles,
    "justGreen" to :: justGreen,
    "intersectionsTest" to :: intersectionsTest,
)
